const TYPE_ACTIONS = {
  CREATE_POST: 'CREATE_POST',
  CREATE_POST_ERROR: 'CREATE_POST_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR'
};

export default TYPE_ACTIONS;
